// svelte-frontend/src/routes/register/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { authStore, setAuthUser } from '$lib/auth/auth-store';
	import { signUp } from '$lib/api/auth';

	let firstName = $state('');
	let lastName = $state('');
	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let loading = $state(false);

	async function handleRegister(e: Event) {
		e.preventDefault();
		error = '';
		if (password !== confirmPassword) {
			error = 'Passwörter stimmen nicht überein.';
			return;
		}
		loading = true;
		try {
			const user = await signUp(firstName, lastName, email, password, confirmPassword);
			setAuthUser(user);
			goto('/inbox');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Registrierung fehlgeschlagen.';
		} finally {
			loading = false;
		}
	}

	$effect(() => {
		if (typeof window !== 'undefined' && $authStore.user) {
			goto('/inbox');
		}
	});
</script>

<svelte:head>
	<title>Registrieren | Venera</title>
</svelte:head>

<div class="flex min-h-[60vh] items-center justify-center">
	<img src="/background.png" alt="Venera" class="absolute top-0 left-0 w-full h-full object-cover" />
	<div class="z-10 text-white mt-40 flex flex-col gap-4 items-center w-full max-w-sm px-4">
		<h1 class="text-4xl font-bold">Venera</h1>
		<p class="text-white/70 text-sm">Konto erstellen</p>

		<form onsubmit={handleRegister} class="w-full flex flex-col gap-3">
			<div class="grid grid-cols-2 gap-3">
				<div class="flex flex-col gap-1">
					<Label for="firstName" class="text-white">Vorname</Label>
					<Input
						id="firstName"
						type="text"
						placeholder="Max"
						bind:value={firstName}
						required
						class="bg-white/10 border-white/30 text-white placeholder:text-white/50"
					/>
				</div>
				<div class="flex flex-col gap-1">
					<Label for="lastName" class="text-white">Nachname</Label>
					<Input
						id="lastName"
						type="text"
						placeholder="Mustermann"
						bind:value={lastName}
						required
						class="bg-white/10 border-white/30 text-white placeholder:text-white/50"
					/>
				</div>
			</div>
			<div class="flex flex-col gap-1">
				<Label for="email" class="text-white">E-Mail</Label>
				<Input
					id="email"
					type="email"
					placeholder="deine@email.de"
					bind:value={email}
					required
					class="bg-white/10 border-white/30 text-white placeholder:text-white/50"
				/>
			</div>
			<div class="flex flex-col gap-1">
				<Label for="password" class="text-white">Passwort</Label>
				<Input
					id="password"
					type="password"
					placeholder="Mindestens 8 Zeichen"
					bind:value={password}
					required
					minlength={8}
					class="bg-white/10 border-white/30 text-white placeholder:text-white/50"
				/>
			</div>
			<div class="flex flex-col gap-1">
				<Label for="confirmPassword" class="text-white">Passwort bestätigen</Label>
				<Input
					id="confirmPassword"
					type="password"
					placeholder="••••••••"
					bind:value={confirmPassword}
					required
					class="bg-white/10 border-white/30 text-white placeholder:text-white/50"
				/>
			</div>
			{#if error}
				<p class="text-red-400 text-sm text-center">{error}</p>
			{/if}
			<Button type="submit" variant="default" class="w-full" disabled={loading}>
				{loading ? 'Registrieren…' : 'Registrieren'}
			</Button>
		</form>

		<p class="text-sm text-white/70">
			Bereits ein Konto?
			<a href="/login" class="text-white underline hover:text-white/80">Anmelden</a>
		</p>
	</div>
</div>

// app/(auth)/register/page.tsx
"use client";

import { useState } from "react";
import { useAuthActions } from "@convex-dev/auth/react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Loader2 } from "lucide-react";

export default function RegisterPage() {
  const { signIn } = useAuthActions();
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setIsLoading(true);

    const formData = new FormData(e.currentTarget);
    const password = formData.get("password") as string;
    const confirmPassword = formData.get("confirmPassword") as string;

    if (password !== confirmPassword) {
      toast.error("Passwörter stimmen nicht überein.");
      setIsLoading(false);
      return;
    }

    try {
      await signIn("password", {
        email: formData.get("email") as string,
        password,
        flow: "signUp",
        name: formData.get("name") as string,
      });
      router.push("/");
    } catch (err) {
      const message = err instanceof Error ? err.message : null;
      toast.error(message ?? "Registrierung fehlgeschlagen. Bitte erneut versuchen.");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <Card className="w-full max-w-sm">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold">Registrieren</CardTitle>
          <CardDescription>Erstelle dein kostenloses Konto</CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input
                id="name"
                name="name"
                type="text"
                placeholder="Max Mustermann"
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">E-Mail</Label>
              <Input
                id="email"
                name="email"
                type="email"
                placeholder="name@beispiel.de"
                required
                autoComplete="email"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Passwort</Label>
              <Input
                id="password"
                name="password"
                type="password"
                required
                autoComplete="new-password"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="confirmPassword">Passwort bestätigen</Label>
              <Input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                required
                autoComplete="new-password"
              />
            </div>
          </CardContent>
          <CardFooter className="flex flex-col gap-3">
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Wird registriert...
                </>
              ) : (
                "Konto erstellen"
              )}
            </Button>
            <p className="text-center text-sm text-muted-foreground">
              Bereits registriert?{" "}
              <Link href="/login" className="underline underline-offset-4">
                Anmelden
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
