// svelte-frontend/src/routes/forgot-password/+page.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { forgotPassword } from '$lib/api/auth';

	let email = $state('');
	let error = $state('');
	let success = $state(false);
	let loading = $state(false);

	async function handleSubmit(e: Event) {
		e.preventDefault();
		error = '';
		loading = true;
		try {
			await forgotPassword(email);
			success = true;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Anfrage fehlgeschlagen.';
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head>
	<title>Passwort vergessen | Venera</title>
</svelte:head>

<div class="flex min-h-[60vh] items-center justify-center">
	<img src="/background.png" alt="Venera" class="absolute top-0 left-0 w-full h-full object-cover" />
	<div class="z-10 text-white mt-60 flex flex-col gap-4 items-center w-full max-w-sm px-4">
		<h1 class="text-4xl font-bold">Venera</h1>
		<p class="text-white/70 text-sm">Passwort zurücksetzen</p>

		{#if success}
			<div class="w-full text-center bg-white/10 border border-white/30 rounded-md p-4">
				<p class="text-white text-sm">
					Falls diese E-Mail-Adresse registriert ist, haben wir einen Reset-Link gesendet.
				</p>
			</div>
		{:else}
			<form onsubmit={handleSubmit} class="w-full flex flex-col gap-3">
				<div class="flex flex-col gap-1">
					<Label for="email" class="text-white">E-Mail</Label>
					<Input
						id="email"
						type="email"
						placeholder="deine@email.de"
						bind:value={email}
						required
						class="bg-white/10 border-white/30 text-white placeholder:text-white/50"
					/>
				</div>
				{#if error}
					<p class="text-red-400 text-sm text-center">{error}</p>
				{/if}
				<Button type="submit" variant="default" class="w-full" disabled={loading}>
					{loading ? 'Senden…' : 'Reset-Link senden'}
				</Button>
			</form>
		{/if}

		<a href="/login" class="text-white/70 hover:text-white text-sm underline">
			Zurück zum Login
		</a>
	</div>
</div>

// app/(auth)/forgot-password/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Loader2, ArrowLeft } from "lucide-react";

export default function ForgotPasswordPage() {
  const [isLoading, setIsLoading] = useState(false);
  const [email, setEmail] = useState("");
  const [sent, setSent] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      // TODO: Convex Auth Reset Password implementieren
      await new Promise((resolve) => setTimeout(resolve, 1000));
      setSent(true);
      toast.success("Reset-Link wurde gesendet");
    } catch {
      toast.error("Fehler beim Senden des Reset-Links");
    } finally {
      setIsLoading(false);
    }
  };

  if (sent) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl">E-Mail gesendet</CardTitle>
          <CardDescription>
            Wir haben dir einen Link zum Zurücksetzen deines Passworts gesendet.
            Bitte prüfe dein E-Mail-Postfach.
          </CardDescription>
        </CardHeader>
        <CardFooter>
          <Link href="/login" className="w-full">
            <Button variant="outline" className="w-full">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Zurück zum Login
            </Button>
          </Link>
        </CardFooter>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-2xl">Passwort vergessen</CardTitle>
        <CardDescription>
          Gib deine E-Mail-Adresse ein und wir senden dir einen Reset-Link
        </CardDescription>
      </CardHeader>
      <form onSubmit={handleSubmit}>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">E-Mail</Label>
            <Input
              id="email"
              type="email"
              placeholder="name@beispiel.de"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>
        </CardContent>
        <CardFooter className="flex flex-col gap-4">
          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Senden...
              </>
            ) : (
              "Reset-Link senden"
            )}
          </Button>
          <Link href="/login" className="w-full">
            <Button variant="ghost" className="w-full">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Zurück zum Login
            </Button>
          </Link>
        </CardFooter>
      </form>
    </Card>
  );
}
